name: AdaMove
channels:
  - conda-forge
dependencies:
  - python=3.10 
  - yaml=0.2.5
  - pytorch=2.5.1
  - torchvision=0.20.1
  - pyyaml=6.0.2
  - numpy=2.1.3
  - pip
  - pip:
    - ray 
    - ray[tune]
    - tqdm


